Update apiBreakTest.yml

diff --git a/.github/workflows/apiBreakTest.yml b/.github/workflows/apiBreakTest.yml
--- a/.github/workflows/apiBreakTest.yml
+++ b/.github/workflows/apiBreakTest.yml
@@ -35,7 +35,6 @@ jobs:
         # Run swift-api-diff commands here directly
         OLD_API_DIR=$(mktemp -d)
         NEW_API_DIR=$(mktemp -d)
-        REPORT_DIR=$(mktemp -d)
         SDK_PATH=$(xcrun --show-sdk-path)
 
         echo "Fetching old version..."
@@ -44,9 +43,9 @@ jobs:
         swift api-digester -sdk "$SDK_PATH" -dump-sdk -module "Amplify" -o "$OLD_API_DIR/old.json" -I .build/debug || { echo "Failed to dump old SDK"; exit 1; }
         
         echo "Fetching new version..."
-        git checkout ${{ github.sha }}
+        git checkout ${{ github.head_ref }}
         git log -1  # Print the commit info for debugging
-        swift build> /dev/null 2>&1 || { echo "Failed to build new version"; exit 1; }
+        swift build > /dev/null 2>&1 || { echo "Failed to build new version"; exit 1; }
         swift api-digester -sdk "$SDK_PATH" -dump-sdk -module "Amplify" -o "$NEW_API_DIR/new.json" -I .build/debug || { echo "Failed to dump new SDK"; exit 1; }
         
         echo "Comparing APIs..."
@@ -55,21 +54,18 @@ jobs:
         # Capture the output for commenting
         api_diff_output=$(cat api-diff-report.txt)
         
-        # Capture the SHA-1 checksum of the file
-        checksum=$(shasum api-diff-report.txt | awk '{ print $1 }')
-        
-        # Print the SHA-1 checksum
-        echo "SHA-1 checksum of $report: $checksum"
-        
-        echo "API_DIFF_OUTPUT<<EOF" >> $GITHUB_ENV
-        if ! echo "$checksum" | grep -q afd2a1b542b33273920d65821deddc653063c700 
-          then 
+        # Check for breaking changes
+        if echo "$api_diff_output" | grep -q "Breaking change"; then
+          echo "API_DIFF_OUTPUT<<EOF" >> $GITHUB_ENV
           echo "❌ Public API Breaking Change detected:" >> $GITHUB_ENV
           echo "$api_diff_output" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
+          echo "BREAKING_CHANGE_DETECTED=true" >> $GITHUB_ENV
         else
+          echo "API_DIFF_OUTPUT<<EOF" >> $GITHUB_ENV
           echo "✅ No Public API Breaking Change detected" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
+          echo "BREAKING_CHANGE_DETECTED=false" >> $GITHUB_ENV
         fi
 
     - name: Comment on PR with API Diff
@@ -92,3 +88,20 @@ jobs:
           } else {
             console.log("No API diff output found.");
           }
+
+    - name: Add Reviewer if Breaking Change Detected
+      if: env.BREAKING_CHANGE_DETECTED == 'true'
+      uses: actions/github-script@v6
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          const issueNumber = context.payload.pull_request.number;
+          const owner = context.repo.owner;
+          const repo = context.repo.repo;
+
+          github.rest.pulls.requestReviewers({
+            owner: owner,
+            repo: repo,
+            pull_number: issueNumber,
+            reviewers: ["rozaychen"]
+          });
